add new policy for getInstitutions and filter on product
pagopa/selfcare-infra pull request #192
Opened 2022-07-29 15:00 UTC by KevinSi96

### List of changes

added new filter on product to the getInstitutionsUsingGet API of the External Api Service

### Motivation and context

need to filter the list of institution based on the onboarded product

### Type of changes

- [ ] Add new resources
- [ ] Update configuration to existing resources
- [ ] Remove existing resources

### Env to apply

- [ ] DEV
- [ ] UAT
- [ ] PROD

### Does this introduce a change to production resources with possible user impact?

- [ ] Yes, users may be impacted applying this change
- [ ] No

### Does this introduce an unwanted change on infrastructure? Check terraform plan execution result

- [ ] Yes
- [ ] No

### Other information

---

### If PR is partially applied, why? (reserved to mantainers)

2022-07-29 15:17 UTC, antonioT90 submitted a review, later dismissed

2022-07-29 15:26 UTC, diegolagospagopa requested changes

2022-07-29 15:26 UTC, diegolagospagopa commented on src/core/apim.tf
>  }
Please Kevin, configure your Editor to put an empty line in each file

2022-07-29 16:28 UTC, antonioT90 approved these changes

2022-08-03 08:17 UTC, rodoviti approved these changes
ACK

2022-08-03 08:28 UTC, rodoviti requested changes
add newline

2022-08-03 08:28 UTC, rodoviti commented on src/core/apim.tf
>  }
```suggestion
}

```

2022-08-03 08:34 UTC, rodoviti approved these changes
ACK

2022-08-03 08:37 UTC, andrea-putzu approved these changes

2022-08-03 08:41 UTC, diegolagospagopa approved these changes

2022-08-03 08:52 UTC, merged